### ISSUE TITLE
IllegalStateException: Unmapped relationship: 7

### ISSUE THREAD

**Issue by mibby** [Technove/AirplaneLite#34]
Airplane-Purpur-1.17 dev 14

Doing some local testing (on windows) and ran into this exception at startup. Does not occur with Tuinity, Purpur, or Paper.

```
[07:37:56] [main/WARN]: Failed retrieving info for group processor
java.lang.IllegalStateException: Unmapped relationship: 7
	at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:3033) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at oshi.driver.windows.LogicalProcessorInformation.getLogicalProcessorInformationEx(LogicalProcessorInformation.java:61) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:155) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:74) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:66) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:61) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at net.minecraft.SystemReport.lambda$putHardware$4(SystemReport.java:74) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at net.minecraft.SystemReport.ignoreErrors(SystemReport.java:81) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at net.minecraft.SystemReport.a(SystemReport.java:74) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at net.minecraft.SystemReport.lambda$new$2(SystemReport.java:51) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at net.minecraft.SystemReport.ignoreErrors(SystemReport.java:81) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at net.minecraft.SystemReport.<init>(SystemReport.java:51) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at net.minecraft.CrashReport.<init>(CrashReport.java:29) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at net.minecraft.CrashReport.preload(CrashReport.java:252) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at net.minecraft.server.Main.main(Main.java:96) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at org.bukkit.craftbukkit.Main.main(Main.java:308) ~[patched_1.17.jar:git-AirplanePurpur-14]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at io.papermc.paperclip.Paperclip.main(Paperclip.java:49) ~[launcher-airplanepurpur.jar:?]
```

**Comment by PaulBGD** [comment]
Related to Flare, we need to just use the provided OSHI instead of shading our own. Will get it fixed sometime today or tomorrow.

**Comment by PaulBGD** [comment]
Should be fixed now.
