### ISSUE TITLE
Incompatibility with LibsDisguises - NoSuchMethodException: net.minecraft.world.effect.MobEffectList.fromId(int)

### ISSUE THREAD

**Issue by mibby** [Technove/AirplaneLite#35]
Airplane-Purpur-1.17 dev 14
LibsDisguises dev 958
ProtocolLib dev 526

LibsDisguises is incompatible with breaking changes in Airplane, caused by missing a class method in the patched jar?

```
[07:38:05] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.effect.MobEffectList.fromId(int)
[07:38:05] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2613)
[07:38:05] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsMethod(ReflectionManager.java:980)
[07:38:05] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsMethod(ReflectionManager.java:992)
[07:38:05] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.init(ReflectionManager.java:140)
[07:38:05] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:210)
[07:38:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[07:38:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[07:38:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[07:38:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[07:38:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[07:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:716)
[07:38:05] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[07:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1193)
[07:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[07:38:05] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

LibsDisguises loads fine with Tuinity-1.17 dev 15 (codemc ci) & Purpur-1.17 dev 1255.

**Comment by PaulBGD** [comment]
I'll look into this in a bit, likely has to do with Paperweight still having issues with remapping.

**Comment by PaulBGD** [comment]
Should be good, try on latest.
