### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by Strahilchu** [Technove/AirplaneLite#66]
[15:05:08 ERROR]: Entity threw exception at world_the_end:-7854.596108512413,61.0,14468.786586750102
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "into" is null
        at io.papermc.paper.util.CollisionUtil.getEntityHardCollisions(CollisionUtil.java:584) ~[patched_1.17.1.jar:git-Airplane-90]
        at io.papermc.paper.util.CollisionUtil.getEntityCollisionsWithCache(CollisionUtil.java:554) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.world.entity.Entity.inBlock(Entity.java:2470) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.world.entity.EntityLiving.inBlock(EntityLiving.java:4079) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.world.entity.EntityLiving.entityBaseTick(EntityLiving.java:396) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.world.entity.EntityInsentient.entityBaseTick(EntityInsentient.java:320) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.world.entity.Entity.tick(Entity.java:726) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2855) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:393) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1129) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:777) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:756) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Airplane-90]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-90]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by PaulBGD** [comment]
Update your Airplane version.
