### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by wcy6457** [Technove/AirplaneLite#70]
[20:10:43 INFO]: [SlimefunItemExpansion] Enabling SlimefunItemExpansion v1.0.0
[20:10:43 INFO]: [SlimefunItemExpansion] SFIE v1.0.0 Enabled.
[20:10:43 ERROR]: Error occurred while enabling SlimefunItemExpansion v1.0.0 (Is it up to date?)
java.lang.ClassCastException: Cannot cast java.lang.String to net.kyori.adventure.text.Component
        at java.lang.Class.cast(Unknown Source) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.common.reflect.Ref.put(Ref.kt:37) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.common.reflect.Reflex.set(Reflex.kt:69) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.common.reflect.Reflex.write(Reflex.kt:36) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.common.reflect.Reflex$Companion.setProperty(Reflex.kt:108) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.common.reflect.Reflex$Companion.setProperty$default(Reflex.kt:104) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:70) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:55) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.platform.BukkitExecutor$submit$1.<init>(BukkitExecutor.kt:39) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.platform.BukkitExecutor.submit(BukkitExecutor.kt:36) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.platform.BukkitExecutor.start(BukkitExecutor.kt:28) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at io.github.itsflicker.slimefunitemexpansion.taboolib.common.platform.FunctionKt.startExecutor(Function.kt:69) ~[SlimefunItemExpansion-1.0.0.jar:?]        at io.github.itsflicker.slimefunitemexpansion.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:64) ~[SlimefunItemExpansion-1.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-103]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-103]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-103]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Airplane-103]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:319) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-103]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[20:10:43 INFO]: [SlimefunItemExpansion] Disabling SlimefunItemExpansion v1.0.0

**Comment by wcy6457** [comment]
airplane 1.17

**Comment by PaulBGD** [comment]
Not an issue with us, ask slimefun to fix.
